[package]
name = "rust-psl"
version = "0.1.0"
authors = ["Roustem Karimov <roustem@agilebits.com>"]
edition = "2018"

[dependencies]
addr = { version = "0.10.2", default-features = false }
psl = "2"

[profile.release]
lto = true
