[package]
name = "rust-publicsuffix"
version = "0.1.0"
authors = ["Roustem Karimov <roustem@agilebits.com>"]
edition = "2018"

[dependencies.addr]
version = "0.10.2"
default-features = false

[dependencies.publicsuffix]
version = "2"
features = ["anycase"]

[profile.release]
lto = true
